init ENV:
    rm -rf .terraform && rm -rf .terraform.lock.hcl && \
    terraform init -backend-config=../backends/{{ENV}}.hcl

plan ENV: 
    terraform workspace select {{ENV}} || terraform workspace new {{ENV}}
    terraform plan -var-file=../variables/{{ENV}}.tfvars -out=../plans/{{ENV}}.plan

apply ENV: 
    terraform workspace select {{ENV}}
    terraform apply ../plans/{{ENV}}.plan

destroy ENV: 
    terraform workspace select {{ENV}}
    terraform destroy -var-file=../variables/{{ENV}}.tfvars
