clean:
    rm -rf .terraform && rm -rf .terraform.lock.hcl && rm -rf ../plans/*

init ENV: 
    terraform init -backend-config=../backends/static-website-{{ENV}}.hcl

plan ENV: (init ENV)
    terraform workspace select {{ENV}} || terraform workspace new {{ENV}}
    terraform plan -var-file=../variables/{{ENV}}.tfvars -out=../plans/static-website-{{ENV}}.plan

apply ENV: 
    terraform workspace select {{ENV}}
    terraform apply ../plans/static-website-{{ENV}}.plan

destroy ENV: 
    terraform workspace select {{ENV}}
    terraform destroy -var-file=../variables/{{ENV}}.tfvars
